# fly.toml app configuration file generated for api-nitter on 2024-02-15T09:31:15+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-nitter'
primary_region = 'iad'

[build]
  image = 'kristobalus/nitter-proxy:latest'

[env]
  HOST = '0.0.0.0'
  PORT = '8080'
#  CONCURRENCY = '5'
#  RETRY_AFTER_MILLIS = '0'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 1000

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
